### ISSUE TITLE
RuntimeError("no devices found")

### ISSUE THREAD

**Issue by schoeler** [jetperch/pyjoulescope#4]
So far I have been using the joulescope_ui program to run tests, and figured I'd give it a try with python. 

`C:\Users\bschoele\AppData\Local\Programs\Python\Python37-32\Scripts>py -m joulescope capture --contiguous 1.0 mycapture.jls
Traceback (most recent call last):
  File "C:\Users\bschoele\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\bschoele\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bschoele\AppData\Local\Programs\Python\Python37-32\lib\site-packages\joulescope\__main__.py", line 22, in <module>
    sys.exit(run())
  File "C:\Users\bschoele\AppData\Local\Programs\Python\Python37-32\lib\site-packages\joulescope\command\runner.py", line 73, in run
    return args.func(args)
  File "C:\Users\bschoele\AppData\Local\Programs\Python\Python37-32\lib\site-packages\joulescope\command\capture.py", line 38, in on_cmd
    device = scan_require_one(name='Joulescope')
  File "C:\Users\bschoele\AppData\Local\Programs\Python\Python37-32\lib\site-packages\joulescope\driver.py", line 1089, in scan_require_one
    raise RuntimeError("no devices found")
RuntimeError: no devices found`

Seems like the driver is having an issue finding the device.  It finds the device OK from Joulescope app, though.  I tried disabling the Joulescope device from the UI and closing the Joulescope App.... but with the same result as above.

**Comment by mliberty1** [comment]
Hi @schoeler - I presume that you are using 32-bit python on 64-bit Windows.  Joulescope requires the same bit python as the OS, so you will need to download and install 64-bit python 3.7.  The development branch code already has a [check for this](https://github.com/jetperch/pyjoulescope/commit/73d186f7b851504de9618944acbe479105da74e5) and [updated docs](https://github.com/jetperch/pyjoulescope/commit/0966aa663f75364faf9581781aafcae8a55ecc5a), but it has not yet been released.
